### ISSUE TITLE
Change delay metric

### ISSUE THREAD

**Issue by makoteq** [makoteq/metaxa#12]
Instead of miliseconds we should measure delay by words per minute (wpm)

**Comment by lukedev820** [comment]
Hi, I'll try and attempt this!

**Comment by makoteq** [comment]
Go for it!

**Comment by lukedev820** [comment]
Not really used to working with args. What line is responsible for the speed?
I believe its 47:
`? args[2] `
But I'm  just making sure

**Comment by makoteq** [comment]
yes, you are right

**Comment by lukedev820** [comment]
Sorry for the delay I had to take care of something. Ive submitted a PR, take a look!

**Comment by lukedev820** [comment]
So sorry for closing the PR im not used to working with merge conflicts. Heres [the resolved pr!](https://github.com/makoteq/metaxa/pull/20)
