### ISSUE TITLE
Add option to paste text

### ISSUE THREAD

**Issue by makoteq** [makoteq/metaxa#17]
Add option for user to paste text directly into the shell, as alternative for specifying path

**Comment by M-Rahul1** [comment]
@makoteq assign this issue to me i will work on it

**Comment by cychu42** [comment]
Hello, is this issue still being worked on? If not, I'm interested to do so.

**Comment by makoteq** [comment]
Go ahead!

**Comment by cychu42** [comment]
Hi, I made a [PR](https://github.com/makoteq/metaxa/pull/25). Let me know what you think. : )
