### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by makoteq** [makoteq/metaxa#22]
Change colors to keep everything consistent.
One color for header and one for content

**Comment by Divjyo15** [comment]
Hi...can you plz elaborate more

**Comment by Subhajit767** [comment]
I want to work on this so please assign this to me

**Comment by makoteq** [comment]
> Hi...can you plz elaborate more


Currently there are multiple colors in different sections.
We want to keep styling consistent by using only two colors

**Comment by makoteq** [comment]
Go ahead @yazh1202

**Comment by yazh1202** [comment]
Please review the PR #28 and suggest any changes if required. Thanks.
