### ISSUE TITLE
Create stats command

### ISSUE THREAD

**Issue by makoteq** [makoteq/metaxa#23]
Create "stats" command:
syntax:
` metaxa stats <path>`
where <path> is path to specified file for which user what to get statistic

Statistic to show:
- number of words
- number of sentences
- absolute path of file

**Comment by NeilAn99** [comment]
Hi, I would like to work on this issue.

**Comment by makoteq** [comment]
Go ahead!

**Comment by NeilAn99** [comment]
Hi, I have created a [pull request](https://github.com/makoteq/metaxa/pull/24), please check it out.
