### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by makoteq** [makoteq/metaxa#26]
Readme needs updated documentation for all newly introduced commands

**Comment by saishubham468** [comment]
Hi , could you please assign this to me. @makoteq

**Comment by makoteq** [comment]
@saishubham468 go ahead!

**Comment by ashutoshjv661** [comment]
Can you assign it to me ? ^_^

**Comment by ashutoshjv661** [comment]
Hi @makoteq I would like to work on this issue ^_^

**Comment by ashutoshjv661** [comment]
I have added a PR for this, please check ^_^
